random_seed: 23
save_dir: ./runs/model_resnet/
batch_size: 1024
config: config.yaml
data_dir: ./dataset/
modelname: resnet50
feature_dim: 2048
anno_filename: styles_by_article.csv
classes_filename: classes.pkl
columns: 
- gender
- masterCategory
- subCategory
- articleType
- baseColour
- season
- usage
resize_res: 100 
crop_res: 80
num_workers: 4
lr: 0.001
num_epoch: 50
device: cuda
